--[[
-- Orca, a free and open-source Roblox script hub.
-- This script was generated by ci/bundle.lua, and is not intended to be modified.
-- To view the source code, see the 'src' folder on GitHub!
--
-- Author: 0866
-- License: MIT
-- Version: "1.1.1"
-- GitHub: https://github.com/richie0866/orca
--]]

local RunService=game:GetService("RunService")
local Players=game:GetService("Players")
local LocalPlayer=Players.LocalPlayer

local Orca={}
Orca.jobs={}

function Orca.jobs.character()
    local character={}
    
    function character.flight()
        local flipper=require(script.Parent.Parent.include.node_modules.flipper.src)
        local GroupMotor=flipper.GroupMotor
        local Spring=flipper.Spring
        
        local flying=false
        local bodyVelocity
        local bodyGyro
        local char=LocalPlayer.Character
        local root=char and char:FindFirstChild("HumanoidRootPart")
        
        local eH=GroupMotor.new({0,0,0},false)
        local targetVelocity=Vector3.new(0,0,0)
        local flySpeed=50
        
        local function updateVelocity()
            if not flying then return end
            local camera=workspace.CurrentCamera
            local moveDir=Vector3.new(0,0,0)
            
            local UIS=game:GetService("UserInputService")
            if UIS:IsKeyDown(Enum.KeyCode.W) then
                moveDir=moveDir+camera.CFrame.LookVector
            end
            if UIS:IsKeyDown(Enum.KeyCode.S) then
                moveDir=moveDir-camera.CFrame.LookVector
            end
            if UIS:IsKeyDown(Enum.KeyCode.A) then
                moveDir=moveDir-camera.CFrame.RightVector
            end
            if UIS:IsKeyDown(Enum.KeyCode.D) then
                moveDir=moveDir+camera.CFrame.RightVector
            end
            if UIS:IsKeyDown(Enum.KeyCode.Space) then
                moveDir=moveDir+Vector3.new(0,1,0)
            end
            if UIS:IsKeyDown(Enum.KeyCode.LeftControl) then
                moveDir=moveDir-Vector3.new(0,1,0)
            end
            
            if moveDir.Magnitude>0 then
                moveDir=moveDir.Unit*flySpeed
            end
            
            targetVelocity=moveDir
        end
        
        RunService.RenderStepped:Connect(function()
            if flying then
                updateVelocity()
                eH:setGoal({Spring.new(targetVelocity.X),Spring.new(targetVelocity.Y),Spring.new(targetVelocity.Z)})
            end
        end)
        
        RunService.Heartbeat:Connect(function(dt)
            if flying then
                eH:step(dt)
                local val=eH:getValue()
                bodyVelocity.Velocity=Vector3.new(val[1],val[2],val[3])
            end
        end)
        
        return {
            start=function()
                if flying then return end
                char=LocalPlayer.Character
                root=char and char:FindFirstChild("HumanoidRootPart")
                if not root then return end
                
                flying=true
                bodyVelocity=Instance.new("BodyVelocity")
                bodyVelocity.MaxForce=Vector3.new(math.huge,math.huge,math.huge)
                bodyVelocity.Velocity=Vector3.new(0,0,0)
                bodyVelocity.Parent=root
                
                bodyGyro=Instance.new("BodyGyro")
                bodyGyro.MaxTorque=Vector3.new(math.huge,math.huge,math.huge)
                bodyGyro.CFrame=root.CFrame
                bodyGyro.Parent=root
                
                eH:start()
            end,
            stop=function()
                if not flying then return end
                flying=false
                eH:stop()
                
                if bodyVelocity then
                    bodyVelocity:Destroy()
                    bodyVelocity=nil
                end
                if bodyGyro then
                    bodyGyro:Destroy()
                    bodyGyro=nil
                end
            end,
            setSpeed=function(speed)
                flySpeed=speed
            end,
            isFlying=function()
                return flying
            end
        }
    end
    
    return character
end

return Orca.jobs
