--[[
-- Orca, a free and open-source Roblox script hub.
-- This script was generated by ci/bundle.lua, and is not intended to be modified.
-- To view the source code, see the 'src' folder on GitHub!
--
-- Author: 0866
-- License: MIT
-- Version: "1.1.1"
-- GitHub: https://github.com/richie0866/orca
--]]

local Rodux=require(script.Parent.Parent.include.node_modules.rodux.src)
local Orca={}
Orca.store={}

function Orca.store.create()
    local initialState={
        ui={
            visible=true,
            minimized=false
        },
        features={
            movement={
                walkSpeedEnabled=false,
                walkSpeed=16,
                jumpHeightEnabled=false,
                jumpHeight=50,
                flyEnabled=false,
                flySpeed=50
            },
            visuals={
                espEnabled=false,
                fullBrightEnabled=false,
                timeOfDay=12
            }
        }
    }
    
    local function reducer(state,action)
        if state==nil then
            state=initialState
        end
        
        if action.type=="SET_UI_VISIBLE" then
            local newState=table.clone(state)
            newState.ui.visible=action.visible
            return newState
        elseif action.type=="SET_UI_MINIMIZED" then
            local newState=table.clone(state)
            newState.ui.minimized=action.minimized
            return newState
        elseif action.type=="SET_WALK_SPEED_ENABLED" then
            local newState=table.clone(state)
            newState.features.movement.walkSpeedEnabled=action.enabled
            return newState
        elseif action.type=="SET_WALK_SPEED" then
            local newState=table.clone(state)
            newState.features.movement.walkSpeed=action.speed
            return newState
        elseif action.type=="SET_JUMP_HEIGHT_ENABLED" then
            local newState=table.clone(state)
            newState.features.movement.jumpHeightEnabled=action.enabled
            return newState
        elseif action.type=="SET_JUMP_HEIGHT" then
            local newState=table.clone(state)
            newState.features.movement.jumpHeight=action.height
            return newState
        elseif action.type=="SET_FLY_ENABLED" then
            local newState=table.clone(state)
            newState.features.movement.flyEnabled=action.enabled
            return newState
        elseif action.type=="SET_FLY_SPEED" then
            local newState=table.clone(state)
            newState.features.movement.flySpeed=action.speed
            return newState
        elseif action.type=="SET_ESP_ENABLED" then
            local newState=table.clone(state)
            newState.features.visuals.espEnabled=action.enabled
            return newState
        elseif action.type=="SET_FULLBRIGHT_ENABLED" then
            local newState=table.clone(state)
            newState.features.visuals.fullBrightEnabled=action.enabled
            return newState
        elseif action.type=="SET_TIME_OF_DAY" then
            local newState=table.clone(state)
            newState.features.visuals.timeOfDay=action.time
            return newState
        end
        
        return state
    end
    
    return Rodux.Store.new(reducer,initialState)
end

return Orca.store
