--[[
-- Orca, a free and open-source Roblox script hub.
-- This script was generated by ci/bundle.lua, and is not intended to be modified.
-- To view the source code, see the 'src' folder on GitHub!
--
-- Author: 0866
-- License: MIT
-- Version: "1.1.1"
-- GitHub: https://github.com/richie0866/orca
--]]

local Roact=require(script.Parent.Parent.include.node_modules.roact.src)
local Hooks=require(script.Parent.Parent.include.node_modules.roact-hooked.out)
local RoduxHooks=require(script.Parent.Parent.include.node_modules.roact-rodux-hooked.out)
local Flipper=require(script.Parent.Parent.include.node_modules.flipper.src)
local Orca={}
Orca.ui={}

local function Button(props)
    return Roact.createElement("TextButton",{
        Size=props.Size or UDim2.new(1,0,0,40),
        Position=props.Position,
        BackgroundColor3=props.BackgroundColor3 or Color3.fromRGB(30,30,35),
        BackgroundTransparency=props.BackgroundTransparency or 0,
        BorderSizePixel=0,
        Text=props.Text or "",
        TextColor3=props.TextColor3 or Color3.fromRGB(255,255,255),
        TextSize=props.TextSize or 14,
        Font=props.Font or Enum.Font.Gotham,
        [Roact.Event.MouseButton1Click]=props.OnClick
    })
end

local function Toggle(props)
    local binding,updateBinding=Roact.createBinding(props.default or false)
    
    return Roact.createElement("Frame",{
        Size=props.Size or UDim2.new(1,0,0,30),
        BackgroundTransparency=1
    },{
        Label=Roact.createElement("TextLabel",{
            Size=UDim2.new(0.7,0,1,0),
            Position=UDim2.new(0,0,0,0),
            BackgroundTransparency=1,
            Text=props.Label or "",
            TextColor3=Color3.fromRGB(255,255,255),
            TextSize=14,
            Font=Enum.Font.Gotham,
            TextXAlignment=Enum.TextXAlignment.Left
        }),
        Toggle=Roact.createElement("TextButton",{
            Size=UDim2.new(0,40,0,20),
            Position=UDim2.new(1,-45,0.5,-10),
            BackgroundColor3=Roact.joinBindings({
                binding,
                Roact.createBinding(Color3.fromRGB(60,60,70)),
                Roact.createBinding(Color3.fromRGB(100,180,100))
            }):map(function(enabled,offColor,onColor)
                return enabled and onColor or offColor
            end),
            BorderSizePixel=0,
            Text="",
            [Roact.Event.MouseButton1Click]=function()
                updateBinding(function(enabled)
                    local newEnabled=not enabled
                    if props.OnChange then
                        props.OnChange(newEnabled)
                    end
                    return newEnabled
                end)
            end
        })
    })
end

local function Slider(props)
    local binding,updateBinding=Roact.createBinding(props.default or 50)
    local motor=Flipper.SingleMotor.new(props.default or 50)
    local onStep=motor:onStep(function(value)
        updateBinding(value)
    end)
    
    return Roact.createElement("Frame",{
        Size=props.Size or UDim2.new(1,0,0,40),
        BackgroundTransparency=1
    },{
        Label=Roact.createElement("TextLabel",{
            Size=UDim2.new(0.7,0,0.5,0),
            Position=UDim2.new(0,0,0,0),
            BackgroundTransparency=1,
            Text=props.Label or "",
            TextColor3=Color3.fromRGB(255,255,255),
            TextSize=14,
            Font=Enum.Font.Gotham,
            TextXAlignment=Enum.TextXAlignment.Left
        }),
        Value=Roact.createElement("TextLabel",{
            Size=UDim2.new(0.3,0,0.5,0),
            Position=UDim2.new(0.7,0,0,0),
            BackgroundTransparency=1,
            Text=Roact.joinBindings({
                binding,
                Roact.createBinding(props.Suffix or "")
            }):map(function(value,suffix)
                return tostring(math.floor(value))..suffix
            end),
            TextColor3=Color3.fromRGB(200,200,200),
            TextSize=14,
            Font=Enum.Font.Gotham,
            TextXAlignment=Enum.TextXAlignment.Right
        }),
        Slider=Roact.createElement("TextButton",{
            Size=UDim2.new(1,0,0,10),
            Position=UDim2.new(0,0,0.5,5),
            BackgroundColor3=Color3.fromRGB(60,60,70),
            BorderSizePixel=0,
            Text="",
            [Roact.Event.MouseButton1Down]=function()
                local UIS=game:GetService("UserInputService")
                local mouse=UIS:GetMouseLocation()
                local slider=script.Parent
                local sliderSize=slider.AbsoluteSize
                local sliderPos=slider.AbsolutePosition
                
                local function update()
                    local mouse=UIS:GetMouseLocation()
                    local relativeX=mouse.X-sliderPos.X
                    local percent=math.clamp(relativeX/sliderSize.X,0,1)
                    local value=props.Min+(props.Max-props.Min)*percent
                    motor:setGoal(Flipper.Instant.new(value))
                    
                    if props.OnChange then
                        props.OnChange(value)
                    end
                end
                
                local connection
                connection=UIS.InputChanged:Connect(function(input)
                    if input.UserInputType==Enum.UserInputType.MouseMovement then
                        update()
                    end
                end)
                
                update()
                
                UIS.InputEnded:Connect(function(input)
                    if input.UserInputType==Enum.UserInputType.MouseButton1 then
                        connection:Disconnect()
                    end
                end)
            end
        })
    })
end

local function Section(props)
    local children={}
    for i,child in ipairs(props.children) do
        children[i]=child
    end
    
    return Roact.createElement("Frame",{
        Size=UDim2.new(1,0,0,props.height or 200),
        BackgroundColor3=Color3.fromRGB(25,25,30),
        BorderSizePixel=0,
        LayoutOrder=props.LayoutOrder
    },{
        Header=Roact.createElement("TextLabel",{
            Size=UDim2.new(1,0,0,30),
            BackgroundColor3=Color3.fromRGB(35,35,40),
            BorderSizePixel=0,
            Text=props.Title or "",
            TextColor3=Color3.fromRGB(255,255,255),
            TextSize=16,
            Font=Enum.Font.GothamBold,
            TextXAlignment=Enum.TextXAlignment.Left
        }),
        Content=Roact.createElement("ScrollingFrame",{
            Size=UDim2.new(1,0,1,-30),
            Position=UDim2.new(0,0,0,30),
            BackgroundTransparency=1,
            BorderSizePixel=0,
            ScrollBarThickness=4,
            ScrollBarImageColor3=Color3.fromRGB(60,60,70)
        },children)
    })
end

local function App(props)
    local store=props.store
    local uiVisible=RoduxHooks.useSelector(function(state)
        return state.ui.visible
    end)
    
    return Roact.createElement("ScreenGui",{
        IgnoreGuiInset=true,
        ResetOnSpawn=false,
        ZIndexBehavior=Enum.ZIndexBehavior.Sibling,
        Enabled=uiVisible
    },{
        Main=Roact.createElement("Frame",{
            Size=UDim2.new(0,500,0,600),
            Position=UDim2.new(0.5,-250,0.5,-300),
            BackgroundColor3=Color3.fromRGB(20,20,25),
            BorderSizePixel=0,
            [Roact.Event.InputBegan]=function(input)
                if input.UserInputType==Enum.UserInputType.MouseButton1 then
                    local UIS=game:GetService("UserInputService")
                    local drag=script.Parent
                    local startPos=input.Position
                    local startDragPos=drag.Position
                    
                    local connection
                    connection=UIS.InputChanged:Connect(function(input)
                        if input.UserInputType==Enum.UserInputType.MouseMovement then
                            local delta=input.Position-startPos
                            drag.Position=startDragPos+UDim2.new(0,delta.X,0,delta.Y)
                        end
                    end)
                    
                    UIS.InputEnded:Connect(function(input)
                        if input.UserInputType==Enum.UserInputType.MouseButton1 then
                            connection:Disconnect()
                        end
                    end)
                end
            end
        },{
            Header=Roact.createElement("Frame",{
                Size=UDim2.new(1,0,0,40),
                BackgroundColor3=Color3.fromRGB(30,30,35),
                BorderSizePixel=0
            },{
                Title=Roact.createElement("TextLabel",{
                    Size=UDim2.new(1,-40,1,0),
                    Position=UDim2.new(0,0,0,0),
                    BackgroundTransparency=1,
                    Text="Orca",
                    TextColor3=Color3.fromRGB(255,255,255),
                    TextSize=18,
                    Font=Enum.Font.GothamBold,
                    TextXAlignment=Enum.TextXAlignment.Left
                }),
                Close=Roact.createElement("TextButton",{
                    Size=UDim2.new(0,40,1,0),
                    Position=UDim2.new(1,-40,0,0),
                    BackgroundTransparency=1,
                    Text="✕",
                    TextColor3=Color3.fromRGB(255,100,100),
                    TextSize=20,
                    Font=Enum.Font.GothamBold,
                    [Roact.Event.MouseButton1Click]=function()
                        store:dispatch({
                            type="SET_UI_VISIBLE",
                            visible=false
                        })
                    end
                })
            }),
            Content=Roact.createElement("ScrollingFrame",{
                Size=UDim2.new(1,0,1,-40),
                Position=UDim2.new(0,0,0,40),
                BackgroundTransparency=1,
                BorderSizePixel=0,
                ScrollBarThickness=4,
                ScrollBarImageColor3=Color3.fromRGB(60,60,70)
            },props.children)
        })
    })
end

Orca.ui.Button=Button
Orca.ui.Toggle=Toggle
Orca.ui.Slider=Slider
Orca.ui.Section=Section
Orca.ui.App=App

return Orca.ui
