--[[
-- Orca, a free and open-source Roblox script hub.
-- This script was generated by ci/bundle.lua, and is not intended to be modified.
-- To view the source code, see the 'src' folder on GitHub!
--
-- Author: 0866
-- License: MIT
-- Version: "1.1.1"
-- GitHub: https://github.com/richie0866/orca
--]]

local Players=game:GetService("Players")
local RunService=game:GetService("RunService")
local UserInputService=game:GetService("UserInputService")
local LocalPlayer=Players.LocalPlayer

-- Load dependencies from GitHub
local function loadGitHub(url)
    local success,result=pcall(function()
        return loadstring(game:HttpGet(url))()
    end)
    if not success then
        error("Failed to load: "..url.."\n"..result)
    end
    return result
end

local RuntimeLib=loadGitHub("https://raw.githubusercontent.com/slizzey/monarch.lua/main/orca_lib/include/RuntimeLib.lua")
local Roact=loadGitHub("https://raw.githubusercontent.com/slizzey/monarch.lua/main/orca_lib/include/node_modules/roact/src.lua")
local Hooks=loadGitHub("https://raw.githubusercontent.com/slizzey/monarch.lua/main/orca_lib/include/node_modules/roact-hooked/out.lua")
local RoduxHooks=loadGitHub("https://raw.githubusercontent.com/slizzey/monarch.lua/main/orca_lib/include/node_modules/roact-rodux-hooked/out.lua")
local OrcaStore=loadGitHub("https://raw.githubusercontent.com/slizzey/monarch.lua/main/orca_lib/include/Orca/store.lua")
local OrcaUI=loadGitHub("https://raw.githubusercontent.com/slizzey/monarch.lua/main/orca_lib/include/Orca/ui.lua")
local OrcaJobs=loadGitHub("https://raw.githubusercontent.com/slizzey/monarch.lua/main/orca_lib/include/Orca/jobs.lua")

-- Initialize store
local store=OrcaStore.create()

-- Initialize jobs
local characterJobs=OrcaJobs.character()
local flightJob=characterJobs.flight()

-- Movement feature handlers
local function handleMovementChanges()
    local state=store:getState()
    local movement=state.features.movement
    local char=LocalPlayer.Character
    local humanoid=char and char:FindFirstChild("Humanoid")
    local root=char and char:FindFirstChild("HumanoidRootPart")
    
    -- Walk Speed
    if humanoid then
        if movement.walkSpeedEnabled then
            humanoid.WalkSpeed=movement.walkSpeed
        else
            humanoid.WalkSpeed=16
        end
    end
    
    -- Jump Height
    if humanoid then
        if movement.jumpHeightEnabled then
            humanoid.JumpPower=movement.jumpHeight
        else
            humanoid.JumpPower=50
        end
    end
    
    -- Fly
    if movement.flyEnabled then
        flightJob.start()
        flightJob.setSpeed(movement.flySpeed)
    else
        flightJob.stop()
    end
end

-- Visual feature handlers
local function handleVisualChanges()
    local state=store:getState()
    local visuals=state.features.visuals
    local lighting=game:GetService("Lighting")
    
    -- Full Bright
    if visuals.fullBrightEnabled then
        lighting.Brightness=2
        lighting.Ambient=Color3.fromRGB(1,1,1)
    else
        lighting.Brightness=1
        lighting.Ambient=Color3.fromRGB(0,0,0)
    end
    
    -- Time of Day
    local hours=math.floor(visuals.timeOfDay)
    local minutes=(visuals.timeOfDay-hours)*60
    lighting.TimeOfDay=string.format("%02d:%02d:00",hours,minutes)
end

-- Listen to store changes
store.changed:connect(function(newState,oldState)
    handleMovementChanges()
    handleVisualChanges()
end)

-- Character respawn handler
LocalPlayer.CharacterAdded:Connect(function(char)
    handleMovementChanges()
end)

-- Toggle UI with keybind
UserInputService.InputBegan:Connect(function(input,gameProcessed)
    if gameProcessed then return end
    if input.KeyCode==Enum.KeyCode.RightControl then
        local state=store:getState()
        store:dispatch({
            type="SET_UI_VISIBLE",
            visible=not state.ui.visible
        })
    end
end)

-- Create UI component with monarch features
local MonarchApp=Hooks.hooked(function(props)
    local store=props.store
    local dispatch=RoduxHooks.useDispatch()
    
    local movement=RoduxHooks.useSelector(function(state)
        return state.features.movement
    end)
    
    local visuals=RoduxHooks.useSelector(function(state)
        return state.features.visuals
    end)
    
    return Roact.createElement(OrcaUI.App,{
        store=store
    },{
        MovementSection=Roact.createElement(OrcaUI.Section,{
            Title="Movement",
            height=300,
            LayoutOrder=1
        },{
            WalkSpeedToggle=Roact.createElement(OrcaUI.Toggle,{
                Label="Walk Speed",
                default=movement.walkSpeedEnabled,
                OnChange=function(enabled)
                    dispatch({
                        type="SET_WALK_SPEED_ENABLED",
                        enabled=enabled
                    })
                end
            }),
            WalkSpeedSlider=Roact.createElement(OrcaUI.Slider,{
                Label="Speed",
                Min=16,
                Max=250,
                Default=movement.walkSpeed,
                Suffix="",
                OnChange=function(value)
                    dispatch({
                        type="SET_WALK_SPEED",
                        speed=value
                    })
                end
            }),
            JumpHeightToggle=Roact.createElement(OrcaUI.Toggle,{
                Label="Jump Height",
                default=movement.jumpHeightEnabled,
                OnChange=function(enabled)
                    dispatch({
                        type="SET_JUMP_HEIGHT_ENABLED",
                        enabled=enabled
                    })
                end
            }),
            JumpHeightSlider=Roact.createElement(OrcaUI.Slider,{
                Label="Height",
                Min=7,
                Max=500,
                Default=movement.jumpHeight,
                Suffix="",
                OnChange=function(value)
                    dispatch({
                        type="SET_JUMP_HEIGHT",
                        height=value
                    })
                end
            }),
            FlyToggle=Roact.createElement(OrcaUI.Toggle,{
                Label="Fly",
                default=movement.flyEnabled,
                OnChange=function(enabled)
                    dispatch({
                        type="SET_FLY_ENABLED",
                        enabled=enabled
                    })
                end
            }),
            FlySpeedSlider=Roact.createElement(OrcaUI.Slider,{
                Label="Fly Speed",
                Min=10,
                Max=300,
                Default=movement.flySpeed,
                Suffix="",
                OnChange=function(value)
                    dispatch({
                        type="SET_FLY_SPEED",
                        speed=value
                    })
                end
            })
        }),
        VisualsSection=Roact.createElement(OrcaUI.Section,{
            Title="Visuals",
            height=250,
            LayoutOrder=2
        },{
            FullBrightToggle=Roact.createElement(OrcaUI.Toggle,{
                Label="Full Bright",
                default=visuals.fullBrightEnabled,
                OnChange=function(enabled)
                    dispatch({
                        type="SET_FULLBRIGHT_ENABLED",
                        enabled=enabled
                    })
                end
            }),
            TimeOfDaySlider=Roact.createElement(OrcaUI.Slider,{
                Label="Time of Day",
                Min=0,
                Max=24,
                Default=visuals.timeOfDay,
                Suffix="h",
                OnChange=function(value)
                    dispatch({
                        type="SET_TIME_OF_DAY",
                        time=value
                    })
                end
            })
        })
    })
end)

-- Mount the UI
local element=Roact.createElement(RoduxHooks.Provider,{
    store=store
},{
    App=Roact.createElement(MonarchApp,{
        store=store
    })
})

local handle=Roact.mount(element,LocalPlayer.PlayerGui,"OrcaUI")

print("Orca loaded successfully!")
print("Press RightControl to toggle the UI")
