--[[
-- Orca, a free and open-source Roblox script hub.
-- This script was generated by ci/bundle.lua, and is not intended to be modified.
-- To view the source code, see the 'src' folder on GitHub!
--
-- Author: 0866
-- License: MIT
-- Version: "1.1.1"
-- GitHub: https://github.com/richie0866/orca
--]]

local n8="Non-promise value passed into %s at index %s"
local n9="Please pass a list of promises to %s"
local na="Please pass a handler function to %s!"
local nb={__mode="k"}
local function nc(nd,ne)
    local nf={}
    for ev,ng in ipairs(ne) do
        nf[ng]=ng
    end
    return setmetatable(nf,{
        __index=function(ev,gX)
            error(string.format("%s is not in %s!",gX,nd),2)
        end,
        __newindex=function()
            error(string.format("Creating new members in %s is not allowed!",nd),2)
        end
    })
end

local nh
do
    nh={
        Kind=nc("Promise.Error.Kind",{"ExecutionError","AlreadyCancelled","NotResolvedInTime","TimedOut"})
    }
    nh.__index=nh
    function nh.new(cL,ni)
        cL=cL or {}
        return setmetatable({
            error=tostring(cL.error) or "[This error has no error text.]",
            trace=cL.trace,
            context=cL.context,
            kind=cL.kind,
            parent=ni,
            createdTick=os.clock(),
            createdTrace=debug.traceback()
        },nh)
    end
    function nh.is(nj)
        if type(nj)=="table" then
            local nk=getmetatable(nj)
            if type(nk)=="table" then
                return rawget(nj,"error")~=nil and type(rawget(nk,"extend"))=="function"
            end
        end
        return false
    end
    function nh.isKind(nj,nl)
        assert(nl~=nil,"Argument #2 to Promise.Error.isKind must not be nil")
        return nh.is(nj) and nj.kind==nl
    end
    function nh:extend(cL)
        cL=cL or {}
        cL.kind=cL.kind or self.kind
        return nh.new(cL,self)
    end
    function nh:getErrorChain()
        local nm={self}
        while nm[#nm].parent do
            table.insert(nm,nm[#nm].parent)
        end
        return nm
    end
    function nh:__tostring()
        local nn={string.format("-- Promise.Error(%s) --",self.kind or "?")}
        for ev,no in ipairs(self:getErrorChain()) do
            table.insert(nn,table.concat({no.trace or no.error,no.context},"\n"))
        end
        return table.concat(nn,"\n")
    end
end

local function np(...)
    return select("#",...),{...}
end

local function nq(nr,...)
    return nr,select("#",...),{...}
end

local function ns(nt)
    assert(nt~=nil)
    return function(dw)
        if type(dw)=="table" then
            return dw
        end
        return nh.new({
            error=dw,
            kind=nh.Kind.ExecutionError,
            trace=debug.traceback(tostring(dw),2),
            context="Promise created at:\n\n"..nt
        })
    end
end

local function nu(nt,da,...)
    return nq(xpcall(da,ns(nt),...))
end

local function nv(nt,da,hy,nw)
    return function(...)
        local nx,ny,dx=nu(nt,da,...)
        if nx then
            hy(unpack(dx,1,ny))
        else
            nw(dx[1])
        end
    end
end

local function nz(ek)
    return next(ek)==nil
end

local nA={
    Error=nh,
    Status=nc("Promise.Status",{"Started","Resolved","Rejected","Cancelled"}),
    _getTime=os.clock,
    _timeEvent=game:GetService("RunService").Heartbeat
}

nA.prototype={}
nA.__index=nA.prototype

function nA._new(nt,da,ni)
    if ni~=nil and not nA.is(ni) then
        error("Argument #2 to Promise.new must be a promise or nil",2)
    end
    local self={
        _source=nt,
        _status=nA.Status.Started,
        _values=nil,
        _valuesLength=-1,
        _unhandledRejection=true,
        _queuedResolve={},
        _queuedReject={},
        _queuedFinally={},
        _cancellationHook=nil,
        _parent=ni,
        _consumers=setmetatable({},nb)
    }
    if ni and ni._status==nA.Status.Started then
        ni._consumers[self]=true
    end
    setmetatable(self,nA)
    local function hy(...)
        self:_resolve(...)
    end
    local function nw(...)
        self:_reject(...)
    end
    local function hz(nB)
        if nB then
            if self._status==nA.Status.Cancelled then
                nB()
            else
                self._cancellationHook=nB
            end
        end
        return self._status==nA.Status.Cancelled
    end
    coroutine.wrap(function()
        local nx,ev,dx=nu(self._source,da,hy,nw,hz)
        if not nx then
            nw(dx[1])
        end
    end)()
    return self
end

function nA.new(nC)
    return nA._new(debug.traceback(nil,2),nC)
end

function nA:__tostring()
    return string.format("Promise(%s)",self:getStatus())
end

function nA.defer(da)
    local nt=debug.traceback(nil,2)
    local dq
    dq=nA._new(nt,function(hy,nw,hz)
        local nD
        nD=nA._timeEvent:Connect(function()
            nD:Disconnect()
            local nx,ev,dx=nu(nt,da,hy,nw,hz)
            if not nx then
                nw(dx[1])
            end
        end)
    end)
    return dq
end
nA.async=nA.defer

function nA.resolve(...)
    local nE,nF=np(...)
    return nA._new(debug.traceback(nil,2),function(hy)
        hy(unpack(nF,1,nE))
    end)
end

function nA.reject(...)
    local nE,nF=np(...)
    return nA._new(debug.traceback(nil,2),function(ev,nw)
        nw(unpack(nF,1,nE))
    end)
end

function nA._try(nt,da,...)
    local nG,nF=np(...)
    return nA._new(nt,function(hy)
        hy(da(unpack(nF,1,nG)))
    end)
end

function nA.try(...)
    return nA._try(debug.traceback(nil,2),...)
end

function nA._all(nt,nH,nI)
    if type(nH)~="table" then
        error(string.format(n9,"Promise.all"),3)
    end
    for k2,dq in pairs(nH) do
        if not nA.is(dq) then
            error(string.format(n8,"Promise.all",tostring(k2)),3)
        end
    end
    if #nH==0 or nI==0 then
        return nA.resolve({})
    end
    return nA._new(nt,function(hy,nw,hz)
        local nJ={}
        local nK={}
        local nL=0
        local nM=0
        local nN=false
        local function nO()
            for ev,dq in ipairs(nK) do
                dq:cancel()
            end
        end
        local function nP(k2,...)
            if nN then
                return
            end
            nL=nL+1
            if nI==nil then
                nJ[k2]=...
            else
                nJ[nL]=...
            end
            if nL>=(nI or #nH) then
                nN=true
                hy(nJ)
                nO()
            end
        end
        hz(nO)
        for k2,dq in ipairs(nH) do
            nK[k2]=dq:andThen(function(...)
                nP(k2,...)
            end,function(...)
                nM=nM+1
                if nI==nil or #nH-nM<nI then
                    nO()
                    nN=true
                    nw(...)
                end
            end)
        end
        if nN then
            nO()
        end
    end)
end

function nA.all(nH)
    return nA._all(debug.traceback(nil,2),nH)
end

function nA.fold(nQ,da,bG)
    assert(type(nQ)=="table","Bad argument #1 to Promise.fold: must be a table")
    assert(type(da)=="function","Bad argument #2 to Promise.fold: must be a function")
    local nR=nA.resolve(bG)
    return nA.each(nQ,function(nS,k2)
        nR=nR:andThen(function(nT)
            return da(nT,nS,k2)
        end)
    end):andThenReturn(nR)
end

function nA.some(nH,nI)
    assert(type(nI)=="number","Bad argument #2 to Promise.some: must be a number")
    return nA._all(debug.traceback(nil,2),nH,nI)
end

function nA.any(nH)
    return nA._all(debug.traceback(nil,2),nH,1):andThen(function(nF)
        return nF[1]
    end)
end

function nA.allSettled(nH)
    if type(nH)~="table" then
        error(string.format(n9,"Promise.allSettled"),2)
    end
    for k2,dq in pairs(nH) do
        if not nA.is(dq) then
            error(string.format(n8,"Promise.allSettled",tostring(k2)),2)
        end
    end
    if #nH==0 then
        return nA.resolve({})
    end
    return nA._new(debug.traceback(nil,2),function(hy,ev,hz)
        local nU={}
        local nK={}
        local nV=0
        local function nP(k2,...)
            nV=nV+1
            nU[k2]=...
            if nV>=#nH then
                hy(nU)
            end
        end
        hz(function()
            for ev,dq in ipairs(nK) do
                dq:cancel()
            end
        end)
        for k2,dq in ipairs(nH) do
            nK[k2]=dq:finally(function(...)
                nP(k2,...)
            end)
        end
    end)
end

function nA.race(nH)
    assert(type(nH)=="table",string.format(n9))
    for k2,dq in pairs(nH) do
        assert(nA.is(dq),string.format(n8,"Promise.race",tostring(k2)))
    end
    return nA._new(debug.traceback(nil,2),function(hy,nw,hz)
        local nK={}
        local nW=false
        local function nO()
            for ev,dq in ipairs(nK) do
                dq:cancel()
            end
        end
        local function nX(da)
            return function(...)
                nO()
                nW=true
                return da(...)
            end
        end
        if hz(nX(nw)) then
            return
        end
        for k2,dq in ipairs(nH) do
            nK[k2]=dq:andThen(nX(hy),nX(nw))
        end
        if nW then
            nO()
        end
    end)
end

function nA.each(nQ,nY)
    assert(type(nQ)=="table",string.format(n9))
    assert(type(nY)=="function",string.format(na,"Promise.each"))
    return nA._new(debug.traceback(nil,2),function(hy,nw,hz)
        local nZ={}
        local n_={}
        local o0=false
        local function nO()
            for ev,o1 in ipairs(n_) do
                o1:cancel()
            end
        end
        hz(function()
            o0=true
            nO()
        end)
        local o2={}
        for c2,d3 in ipairs(nQ) do
            if nA.is(d3) then
                if d3:getStatus()==nA.Status.Cancelled then
                    nO()
                    return nw(nh.new({
                        error="Promise is cancelled",
                        kind=nh.Kind.AlreadyCancelled,
                        context=string.format("The Promise that was part of the array at index %d passed into Promise.each was already cancelled when Promise.each began.\n\nThat Promise was created at:\n\n%s",c2,d3._source)
                    }))
                elseif d3:getStatus()==nA.Status.Rejected then
                    nO()
                    return nw(select(2,d3:await()))
                end
                local o3=d3:andThen(function(...)
                    return ...
                end)
                table.insert(n_,o3)
                o2[c2]=o3
            else
                o2[c2]=d3
            end
        end
        for c2,d3 in ipairs(o2) do
            if nA.is(d3) then
                local nr
                nr,d3=d3:await()
                if not nr then
                    nO()
                    return nw(d3)
                end
            end
            if o0 then
                return
            end
            local o4=nA.resolve(nY(d3,c2))
            table.insert(n_,o4)
            local nr,dx=o4:await()
            if not nr then
                nO()
                return nw(dx)
            end
            nZ[c2]=dx
        end
        hy(nZ)
    end)
end

function nA.is(fd)
    if type(fd)~="table" then
        return false
    end
    local o5=getmetatable(fd)
    if o5==nA then
        return true
    elseif o5==nil then
        return type(fd.andThen)=="function"
    elseif type(o5)=="table" and type(rawget(o5,"__index"))=="table" and type(rawget(rawget(o5,"__index"),"andThen"))=="function" then
        return true
    end
    return false
end

function nA.promisify(da)
    return function(...)
        return nA._try(debug.traceback(nil,2),da,...)
    end
end

do
    local o6
    local nD
    function nA.delay(mc)
        assert(type(mc)=="number","Bad argument #1 to Promise.delay, must be a number.")
        if not(mc>=1/60) or mc==math.huge then
            mc=1/60
        end
        return nA._new(debug.traceback(nil,2),function(hy,ev,hz)
            local o7=nA._getTime()
            local o8=o7+mc
            local o9={resolve=hy,startTime=o7,endTime=o8}
            if nD==nil then
                o6=o9
                nD=nA._timeEvent:Connect(function()
                    local oa=nA._getTime()
                    while o6~=nil and o6.endTime<oa do
                        local hE=o6
                        o6=hE.next
                        if o6==nil then
                            nD:Disconnect()
                            nD=nil
                        else
                            o6.previous=nil
                        end
                        hE.resolve(nA._getTime()-hE.startTime)
                    end
                end)
            else
                if o6.endTime<o8 then
                    local hE=o6
                    local next=hE.next
                    while next~=nil and next.endTime<o8 do
                        hE=next
                        next=hE.next
                    end
                    hE.next=o9
                    o9.previous=hE
                    if next~=nil then
                        o9.next=next
                        next.previous=o9
                    end
                else
                    o9.next=o6
                    o6.previous=o9
                    o6=o9
                end
            end
            hz(function()
                local next=o9.next
                if o6==o9 then
                    if next==nil then
                        nD:Disconnect()
                        nD=nil
                    else
                        next.previous=nil
                    end
                    o6=next
                else
                    local ob=o9.previous
                    ob.next=next
                    if next~=nil then
                        next.previous=ob
                    end
                end
            end)
        end)
    end
    function nA.prototype:timeout(mc,oc)
        local nt=debug.traceback(nil,2)
        return nA.race({
            nA.delay(mc):andThen(function()
                return nA.reject(oc==nil and nh.new({
                    kind=nh.Kind.TimedOut,
                    error="Timed out",
                    context=string.format("Timeout of %d seconds exceeded.\n:timeout() called at:\n\n%s",mc,nt)
                }) or oc)
            end),
            self
        })
    end
    function nA.prototype:getStatus()
        return self._status
    end
    function nA.prototype:_andThen(nt,od,oe)
        self._unhandledRejection=false
        return nA._new(nt,function(hy,nw)
            local of=hy
            if od then
                of=nv(nt,od,hy,nw)
            end
            local og=nw
            if oe then
                og=nv(nt,oe,hy,nw)
            end
            if self._status==nA.Status.Started then
                table.insert(self._queuedResolve,of)
                table.insert(self._queuedReject,og)
            elseif self._status==nA.Status.Resolved then
                of(unpack(self._values,1,self._valuesLength))
            elseif self._status==nA.Status.Rejected then
                og(unpack(self._values,1,self._valuesLength))
            elseif self._status==nA.Status.Cancelled then
                nw(nh.new({
                    error="Promise is cancelled",
                    kind=nh.Kind.AlreadyCancelled,
                    context="Promise created at\n\n"..nt
                }))
            end
        end,self)
    end
    function nA.prototype:andThen(od,oe)
        assert(od==nil or type(od)=="function",string.format(na,"Promise:andThen"))
        assert(oe==nil or type(oe)=="function",string.format(na,"Promise:andThen"))
        return self:_andThen(debug.traceback(nil,2),od,oe)
    end
    function nA.prototype:catch(og)
        assert(og==nil or type(og)=="function",string.format(na,"Promise:catch"))
        return self:_andThen(debug.traceback(nil,2),nil,og)
    end
    function nA.prototype:tap(oh)
        assert(type(oh)=="function",string.format(na,"Promise:tap"))
        return self:_andThen(debug.traceback(nil,2),function(...)
            local oi=oh(...)
            if nA.is(oi) then
                local nE,nF=np(...)
                return oi:andThen(function()
                    return unpack(nF,1,nE)
                end)
            end
            return ...
        end)
    end
    function nA.prototype:andThenCall(da,...)
        assert(type(da)=="function",string.format(na,"Promise:andThenCall"))
        local nE,nF=np(...)
        return self:_andThen(debug.traceback(nil,2),function()
            return da(unpack(nF,1,nE))
        end)
    end
    function nA.prototype:andThenReturn(...)
        local nE,nF=np(...)
        return self:_andThen(debug.traceback(nil,2),function()
            return unpack(nF,1,nE)
        end)
    end
    function nA.prototype:cancel()
        if self._status~=nA.Status.Started then
            return
        end
        self._status=nA.Status.Cancelled
        if self._cancellationHook then
            self._cancellationHook()
        end
        if self._parent then
            self._parent:_consumerCancelled(self)
        end
        for fo in pairs(self._consumers) do
            fo:cancel()
        end
        self:_finalize()
    end
    function nA.prototype:_consumerCancelled(oj)
        if self._status~=nA.Status.Started then
            return
        end
        self._consumers[oj]=nil
        if next(self._consumers)==nil then
            self:cancel()
        end
    end
    function nA.prototype:_finally(nt,ok,ol)
        if not ol then
            self._unhandledRejection=false
        end
        return nA._new(nt,function(hy,nw)
            local om=hy
            if ok then
                om=nv(nt,ok,hy,nw)
            end
            if ol then
                local da=om
                om=function(...)
                    if self._status==nA.Status.Rejected then
                        return hy(self)
                    end
                    return da(...)
                end
            end
            if self._status==nA.Status.Started then
                table.insert(self._queuedFinally,om)
            else
                om(self._status)
            end
        end,self)
    end
    function nA.prototype:finally(ok)
        assert(ok==nil or type(ok)=="function",string.format(na,"Promise:finally"))
        return self:_finally(debug.traceback(nil,2),ok)
    end
    function nA.prototype:finallyCall(da,...)
        assert(type(da)=="function",string.format(na,"Promise:finallyCall"))
        local nE,nF=np(...)
        return self:_finally(debug.traceback(nil,2),function()
            return da(unpack(nF,1,nE))
        end)
    end
    function nA.prototype:finallyReturn(...)
        local nE,nF=np(...)
        return self:_finally(debug.traceback(nil,2),function()
            return unpack(nF,1,nE)
        end)
    end
    function nA.prototype:done(ok)
        assert(ok==nil or type(ok)=="function",string.format(na,"Promise:done"))
        return self:_finally(debug.traceback(nil,2),ok,true)
    end
    function nA.prototype:doneCall(da,...)
        assert(type(da)=="function",string.format(na,"Promise:doneCall"))
        local nE,nF=np(...)
        return self:_finally(debug.traceback(nil,2),function()
            return da(unpack(nF,1,nE))
        end,true)
    end
    function nA.prototype:doneReturn(...)
        local nE,nF=np(...)
        return self:_finally(debug.traceback(nil,2),function()
            return unpack(nF,1,nE)
        end,true)
    end
    function nA.prototype:awaitStatus()
        self._unhandledRejection=false
        if self._status==nA.Status.Started then
            local on=Instance.new("BindableEvent")
            self:finally(function()
                on:Fire()
            end)
            on.Event:Wait()
            on:Destroy()
        end
        if self._status==nA.Status.Resolved then
            return self._status,unpack(self._values,1,self._valuesLength)
        elseif self._status==nA.Status.Rejected then
            return self._status,unpack(self._values,1,self._valuesLength)
        end
        return self._status
    end
    local function oo(dZ,...)
        return dZ==nA.Status.Resolved,...
    end
    function nA.prototype:await()
        return oo(self:awaitStatus())
    end
    local function op(dZ,...)
        if dZ~=nA.Status.Resolved then
            error(...==nil and "Expected Promise rejected with no value." or ...,3)
        end
        return ...
    end
    function nA.prototype:expect()
        return op(self:awaitStatus())
    end
    nA.prototype.awaitValue=nA.prototype.expect
    function nA.prototype:_unwrap()
        if self._status==nA.Status.Started then
            error("Promise has not been resolved or rejected.",2)
        end
        local nr=self._status==nA.Status.Resolved
        return nr,unpack(self._values,1,self._valuesLength)
    end
    function nA.prototype:_resolve(...)
        if self._status~=nA.Status.Started then
            if nA.is(...) then
                (...):_consumerCancelled(self)
            end
            return
        end
        if nA.is(...) then
            if select("#",...)>1 then
                local oq=string.format("When returning a Promise from andThen, extra arguments are ".."discarded! See:\n\n%s",self._source)
                warn(oq)
            end
            local ot=...
            local dq=ot:andThen(function(...)
                self:_resolve(...)
            end,function(...)
                local ou=ot._values[1]
                if ot._error then
                    ou=nh.new({
                        error=ot._error,
                        kind=nh.Kind.ExecutionError,
                        context="[No stack trace available as this value originated from an older version of the Promise library (< v2)]"
                    })
                end
                if nh.isKind(ou,nh.Kind.ExecutionError) then
                    return self:_reject(ou:extend({
                        error="This Promise was chained to a Promise that errored.",
                        trace="",
                        context=string.format("The Promise at:\n\n%s\n...Rejected because it was chained to the following Promise, which encountered an error:\n",self._source)
                    }))
                end
                self:_reject(...)
            end)
            if dq._status==nA.Status.Cancelled then
                self:cancel()
            elseif dq._status==nA.Status.Started then
                self._parent=dq
                dq._consumers[self]=true
            end
            return
        end
        self._status=nA.Status.Resolved
        self._valuesLength,self._values=np(...)
        for ev,da in ipairs(self._queuedResolve) do
            coroutine.wrap(da)(...)
        end
        self:_finalize()
    end
    function nA.prototype:_reject(...)
        if self._status~=nA.Status.Started then
            return
        end
        self._status=nA.Status.Rejected
        self._valuesLength,self._values=np(...)
        if not nz(self._queuedReject) then
            for ev,da in ipairs(self._queuedReject) do
                coroutine.wrap(da)(...)
            end
        else
            local dw=tostring(...)
            coroutine.wrap(function()
                nA._timeEvent:Wait()
                if not self._unhandledRejection then
                    return
                end
                local oq=string.format("Unhandled Promise rejection:\n\n%s\n\n%s",dw,self._source)
                if nA.TEST then
                    return
                end
                warn(oq)
            end)()
        end
        self:_finalize()
    end
    function nA.prototype:_finalize()
        for ev,da in ipairs(self._queuedFinally) do
            coroutine.wrap(da)(self._status)
        end
        self._queuedFinally=nil
        self._queuedReject=nil
        self._queuedResolve=nil
        if not nA.TEST then
            self._parent=nil
            self._consumers=nil
        end
    end
    function nA.prototype:now(oc)
        local nt=debug.traceback(nil,2)
        if self:getStatus()==nA.Status.Resolved then
            return self:_andThen(nt,function(...)
                return ...
            end)
        else
            return nA.reject(oc==nil and nh.new({
                kind=nh.Kind.NotResolvedInTime,
                error="This Promise was not resolved in time for :now()",
                context=":now() was called at:\n\n"..nt
            }) or oc)
        end
    end
    function nA.retry(da,ov,...)
        assert(type(da)=="function","Parameter #1 to Promise.retry must be a function")
        assert(type(ov)=="number","Parameter #2 to Promise.retry must be a number")
        local kx,nE={...},select("#",...)
        return nA.resolve(da(...)):catch(function(...)
            if ov>0 then
                return nA.retry(da,ov-1,unpack(kx,1,nE))
            else
                return nA.reject(...)
            end
        end)
    end
    function nA.fromEvent(ow,nY)
        nY=nY or function()
            return true
        end
        return nA._new(debug.traceback(nil,2),function(hy,nw,hz)
            local nD
            local ox=false
            local function oy()
                nD:Disconnect()
                nD=nil
            end
            nD=ow:Connect(function(...)
                local oz=nY(...)
                if oz==true then
                    hy(...)
                    if nD then
                        oy()
                    else
                        ox=true
                    end
                elseif type(oz)~="boolean" then
                    error("Promise.fromEvent predicate should always return a boolean")
                end
            end)
            if ox and nD then
                return oy()
            end
            hz(function()
                oy()
            end)
        end)
    end
end

return nA
