--[[
-- Orca, a free and open-source Roblox script hub.
-- This script was generated by ci/bundle.lua, and is not intended to be modified.
-- To view the source code, see the 'src' folder on GitHub!
--
-- Author: 0866
-- License: MIT
-- Version: "1.1.1"
-- GitHub: https://github.com/richie0866/orca
--]]

local nA=require(script.Parent.Promise)
local ez=game:GetService("RunService")
local oA=game:GetService("ReplicatedFirst")
local a={}
a.Promise=nA

local function oB(fd)
    return ez:IsStudio() and fd:FindFirstAncestorWhichIsA("Plugin")~=nil
end

function a.getModule(fd,oC,oD)
    if oD==nil then
        oD=oC
        oC="@rbxts"
    end
    if ez:IsRunning() and fd:IsDescendantOf(oA) then
        warn("roblox-ts packages should not be used from ReplicatedFirst!")
    end
    if ez:IsRunning() and ez:IsClient() and not oB(fd) and not game:IsLoaded() then
        game.Loaded:Wait()
    end
    local oE=script.Parent:FindFirstChild("node_modules")
    if not oE then
        error("Could not find any modules!",2)
    end
    repeat
        local oF=fd:FindFirstChild("node_modules")
        if oF and oF~=oE then
            oF=oF:FindFirstChild("@rbxts")
        end
        if oF then
            local oG=oF:FindFirstChild(oD)
            if oG then
                return oG
            end
        end
        fd=fd.Parent
    until fd==nil or fd==oE
    local oH=oE:FindFirstChild(oC or "@rbxts")
    return (oH or oE):FindFirstChild(oD) or error("Could not find module: "..oD,2)
end

local oI={}
local oJ={}
function a.import(oK,oG,...)
    for k2=1,select("#",...) do
        oG=oG:WaitForChild(select(k2,...))
    end
    if oG.ClassName~="ModuleScript" then
        error("Failed to import! Expected ModuleScript, got "..oG.ClassName,2)
    end
    oI[oK]=oG
    local oL=oG
    local oM=0
    while oL do
        oM=oM+1
        oL=oI[oL]
        if oL==oG then
            local oN=oL.Name
            for ev=1,oM do
                oL=oI[oL]
                oN=oN.."  ⇒ "..oL.Name
            end
            error("Failed to import! Detected a circular dependency chain: "..oN,2)
        end
    end
    if not oJ[oG] then
        if _G[oG] then
            error("Invalid module access! Do you have two TS runtimes trying to import this? "..oG:GetFullName(),2)
        end
        _G[oG]=a
        oJ[oG]=true
    end
    local hG=require(oG)
    if oI[oK]==oG then
        oI[oK]=nil
    end
    return hG
end

function a.instanceof(hV,oO)
    if type(oO)=="table" and type(oO.instanceof)=="function" then
        return oO.instanceof(hV)
    end
    if type(hV)=="table" then
        hV=getmetatable(hV)
        while hV~=nil do
            if hV==oO then
                return true
            end
            local oP=getmetatable(hV)
            if oP then
                hV=oP.__index
            else
                hV=nil
            end
        end
    end
    return false
end

function a.async(da)
    return function(...)
        local kp=select("#",...)
        local kx={...}
        return nA.new(function(hy,nw)
            coroutine.wrap(function()
                local nx,dx=pcall(da,unpack(kx,1,kp))
                if nx then
                    hy(dx)
                else
                    nw(dx)
                end
            end)()
        end)
    end
end

function a.await(dq)
    if not nA.is(dq) then
        return dq
    end
    local dZ,d3=dq:awaitStatus()
    if dZ==nA.Status.Resolved then
        return d3
    elseif dZ==nA.Status.Rejected then
        error(d3,2)
    else
        error("The awaited Promise was cancelled",2)
    end
end

function a.bit_lrsh(hD,dG)
    local oQ=math.abs(hD)
    local dx=bit32.rshift(oQ,dG)
    if hD==oQ then
        return dx
    else
        return -dx-1
    end
end

a.TRY_RETURN=1
a.TRY_BREAK=2
a.TRY_CONTINUE=3

function a.try(oR,oS,oT)
    local dw,nt
    local nr,oU,oV=xpcall(oR,function(oW)
        dw=oW
        nt=debug.traceback()
    end)
    if not nr and oS then
        local oX,oY=oS(dw,nt)
        if oX then
            oU,oV=oX,oY
        end
    end
    if oT then
        local oX,oY=oT()
        if oX then
            oU,oV=oX,oY
        end
    end
    return oU,oV
end

function a.generator(da)
    local oZ=coroutine.create(da)
    return {
        next=function(...)
            if coroutine.status(oZ)=="dead" then
                return {done=true}
            else
                local nr,d3=coroutine.resume(oZ,...)
                if nr==false then
                    error(d3,2)
                end
                return {value=d3,done=coroutine.status(oZ)=="dead"}
            end
        end
    }
end

return a
